/**
 * plan-status-gate.test.mjs — tools/pre-execute plan-status completed gate
 * unit suite (dsh-plugin M3-WI13, plan
 * `docs/plans/dsh-plugin/2026-08-23-1852-3-pre-execute-plan-status-gate.md`
 * Phase 2 Proof).
 *
 * Branches pinned (plan Phase 2 items):
 *   1. trigger surface: file-write tool shapes (write / edit /
 *      str_replace_editor create|str_replace|insert) × plan-status line
 *      hit/miss × directionality (only → completed gated) ×
 *      create-with-completed × bold/case variants (PLAN_STATUS_RE anchoring).
 *   2. evidence truth table: every legal closure path's run-state fixture →
 *      allow — F1 in-flight (subflow child `status:"running"` + init-time
 *      `forEachItem`), F2 CLOSURE_AUDIT closed visit, F3 BUILD_VERIFY /
 *      subflow completed; evidence surface with NO face → deny + reason;
 *      different-plan subflow / no run-state at all → allow + note (D3).
 *   3. fixture authenticity (iter2 N1 rule): every run-state fixture is
 *      GENERATED by the real bundled engine's own writers
 *      (`_initWorkflow` / `_wfOpen` / `_wfClose` / `_finalizeWorkflow`),
 *      never hand-drawn JSON — plus an explicit shape assertion mirroring
 *      the engine.js init write (forEachItem + status:"running" + pid on
 *      disk BEFORE any step closes).
 *   4. path domain + normalization (iter3 N2): default docs/plans,
 *      missions/*.json custom plansDir, non-plan .md passthrough; relative
 *      target path vs absolute forEachItem; `..` segment normalization.
 *   5. zero-overhead passthrough: edit calls whose old/new strings cannot
 *      touch a status line never read disk (counting IO seam); non-write
 *      tools pass straight through.
 *   6. wiring shape: registerPlanStatusGate subscribes to
 *      'tools/pre-execute' (fake ctx capture), deny decision returned
 *      verbatim { kind:'deny', reason }, allow delegates to next(), cordis
 *      disposer returned.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { evaluatePlanStatusGate, registerPlanStatusGate, fsGateIo } from "../src/plan-status-gate.ts";
import { FlowEngine } from "../assets/src/engine.js";

/* ── scratch project factory ─────────────────────────────────────────────── */

function tmpProject() {
  return mkdtempSync(join(tmpdir(), "plan-status-gate-"));
}

function writePlan(root, rel, status = "active") {
  const p = join(root, rel);
  mkdirSync(join(p, ".."), { recursive: true });
  writeFileSync(p, `# Plan\n\n> Plan Status: ${status}\n\nbody\n`, "utf8");
  return p;
}

/* ── REAL-engine fixture generation (fixture authenticity rule) ──────────── */

/**
 * Drive the REAL bundled FlowEngine's run-state writers to produce one
 * subflow child file under <root>/_tmp/<runId>/run-state-<subflowId>.json
 * whose forEachItem is the given plan path. Stage vocabulary:
 *   "init"        → _initWorkflow only (the in-flight shape the engine
 *                   persists at child init: forEachItem + status running)
 *   "execute"     → init + one closed EXECUTE step (post-EXECUTE, still
 *                   running — no closure face except F1)
 *   "closure"     → init + closed CLOSURE_AUDIT visit (F2)
 *   "fastpath"    → init + closed BUILD_VERIFY + finalize completed (F3)
 *   "failed"      → init + closed EXECUTE + finalize failed (deny face)
 */
function engineSubflowFixture(root, runId, planPath, stage) {
  const runDir = join(root, "_tmp", runId);
  mkdirSync(runDir, { recursive: true });
  const subflowId = "EXEC_PLANS-1-0";
  const engine = new FlowEngine({ name: "plan-execution", entry: "EXECUTE", steps: {} }, {
    config: { runDir, subflowId },
    vars: { forEachItem: planPath },
  });
  engine.runId = runId;
  engine.missionName = "demo";
  engine._initWorkflow();
  if (stage === "execute" || stage === "failed") {
    engine._wfOpen("EXECUTE", 1);
    engine._wfClose("pass", "completed");
  }
  if (stage === "closure") {
    engine._wfOpen("CLOSURE_AUDIT", 1);
    engine._wfClose("approved", "completed");
  }
  if (stage === "fastpath") {
    engine._wfOpen("BUILD_VERIFY", 1);
    engine._wfClose("pass", "completed");
  }
  if (stage === "fastpath") engine._finalizeWorkflow("completed");
  if (stage === "failed") engine._finalizeWorkflow("failed");
  return join(runDir, `run-state-${subflowId}.json`);
}

/** Counting IO wrapper — pins the zero-disk-read passthrough property. */
function countingIo(io = fsGateIo) {
  const counts = { readTextFile: 0, listDirEntries: 0 };
  return {
    counts,
    readTextFile(p) { counts.readTextFile++; return io.readTextFile(p); },
    listDirEntries(p) { counts.listDirEntries++; return io.listDirEntries(p); },
    isDirectory: (p) => io.isDirectory(p),
    realPath: (p) => io.realPath(p),
  };
}

const PLAN_REL = "docs/plans/demo/x.md";

/* ── 1. trigger surface ──────────────────────────────────────────────────── */

test("write tool: draft/active targets pass (directionality)", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    for (const status of ["draft", "active", "planned"]) {
      const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: `> Plan Status: ${status}\n` } }, fsGateIo);
      assert.equal(d.kind, "allow");
      assert.equal(d.note, undefined);
    }
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("write tool: completed on tracked-unclosed plan → deny with structured reason", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "deny");
    assert.match(d.reason, /plan-status gate.*denied/);
    assert.match(d.reason, /CLOSURE_AUDIT/);
    assert.match(d.reason, /BUILD_VERIFY/);
    assert.ok(d.reason.includes(resolve(plan)));
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("write tool: bold and case variants are matched via PLAN_STATUS_RE", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    for (const line of ["> **Plan Status**: completed", "> plan status: COMPLETED", "> Status: *completed*"]) {
      const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: `# x\n\n${line}\n` } }, fsGateIo);
      assert.equal(d.kind, "deny", `line must trigger: ${line}`);
    }
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("write tool: create-with-completed on never-tracked path → allow + D3 note", () => {
  const root = tmpProject();
  try {
    const plan = join(root, "docs", "plans", "new", "y.md");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
    assert.match(d.note, /no run-state evidence surface/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("edit tool: status-line replacement draft→completed is gated", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "draft");
    engineSubflowFixture(root, "r1", plan, "failed");
    const d = evaluatePlanStatusGate({
      name: "edit",
      arguments: { file_path: plan, old_string: "> Plan Status: draft", new_string: "> Plan Status: completed" },
    }, fsGateIo);
    assert.equal(d.kind, "deny");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("edit tool: body edit without status mention passes and reads NO disk", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "draft");
    engineSubflowFixture(root, "r1", plan, "failed");
    const io = countingIo();
    const d = evaluatePlanStatusGate({
      name: "edit",
      arguments: { file_path: plan, old_string: "old body line", new_string: "new body line" },
    }, io);
    assert.equal(d.kind, "allow");
    assert.equal(io.counts.readTextFile, 0, "non-status edit must not read disk");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("edit tool: status-mentioning edit whose result is NOT completed passes (review draft→active)", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "draft");
    engineSubflowFixture(root, "r1", plan, "failed");
    const d = evaluatePlanStatusGate({
      name: "edit",
      arguments: { file_path: plan, old_string: "> Plan Status: draft", new_string: "> Plan Status: active" },
    }, fsGateIo);
    assert.equal(d.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("str_replace_editor: create with completed is gated; str_replace draft→completed is gated", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "draft");
    engineSubflowFixture(root, "r1", plan, "failed");
    const fresh = join(root, "docs", "plans", "demo", "z.md");
    const create = evaluatePlanStatusGate({
      name: "str_replace_editor",
      arguments: { command: "create", path: fresh, file_text: "> Plan Status: completed\n" },
    }, fsGateIo);
    // fresh path is never-tracked → D3 allow+note; the gating itself is
    // asserted through the tracked path below.
    assert.equal(create.kind, "allow");
    assert.match(create.note, /no run-state evidence surface/);
    const replace = evaluatePlanStatusGate({
      name: "str_replace_editor",
      arguments: { command: "str_replace", path: plan, old_str: "> Plan Status: draft", new_str: "> Plan Status: completed" },
    }, fsGateIo);
    assert.equal(replace.kind, "deny");
    // view command is not a write — passthrough.
    const view = evaluatePlanStatusGate({
      name: "str_replace_editor",
      arguments: { command: "view", path: plan },
    }, fsGateIo);
    assert.equal(view.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("non-write tools and non-markdown targets pass straight through", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    assert.equal(evaluatePlanStatusGate({ name: "bash", arguments: { command: "sed -i s/draft/completed/ x.md" } }, fsGateIo).kind, "allow");
    assert.equal(evaluatePlanStatusGate({ name: "read", arguments: { file_path: plan } }, fsGateIo).kind, "allow");
    assert.equal(evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan + ".txt", content: "> Plan Status: completed\n" } }, fsGateIo).kind, "allow");
    assert.equal(evaluatePlanStatusGate({ name: "write", arguments: {} }, fsGateIo).kind, "allow");
    assert.equal(evaluatePlanStatusGate({ name: "write", arguments: null }, fsGateIo).kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

/* ── 2. evidence truth table (fixtures generated by the real engine) ─────── */

test("fixture authenticity: init-stage engine write mirrors engine.js :430-441 shape on disk", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    const file = engineSubflowFixture(root, "r-init", plan, "init");
    const state = JSON.parse(fsGateIo.readTextFile(file));
    assert.equal(state.forEachItem, resolve(plan), "forEachItem persisted at init (absolute plan path)");
    assert.equal(state.status, "running", "status running persisted at init");
    assert.equal(typeof state.pid, "number", "pid persisted for stale-run adjudication");
    assert.ok(Array.isArray(state.steps), "steps[] array present");
    assert.equal(state.runDir, join(root, "_tmp", "r-init"));
    assert.match(basename(file), /^run-state-EXEC_PLANS-1-0\.json$/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("F1 in-flight: subflow child running (init shape) → allow", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "init");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("F1 in-flight: post-EXECUTE still running → allow (execute.md step 4a window)", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "execute");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("F2 post-hoc: closed CLOSURE_AUDIT visit → allow", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "closure");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("F3 post-hoc fast path: BUILD_VERIFY completed / subflow completed → allow", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "fastpath");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("deny: tracked plan, terminal failed closure, no face → deny", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "deny");
    assert.match(d.reason, /_tmp/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("evidence surface is per-plan: different plan's subflow → allow + D3 note", () => {
  const root = tmpProject();
  try {
    const other = writePlan(root, "docs/plans/demo/other.md", "active");
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", other, "failed");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
    assert.match(d.note, /no run-state evidence surface/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("no run-state anywhere (never-ran project) → allow + D3 note", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
    assert.match(d.note, /no run-state evidence surface/);
    assert.match(d.note, /D3/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("stale running (crashed run) → allow — recorded miss face F1 residual", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    // "init" stage never finalizes: mirrors a crashed run's leftover shape.
    engineSubflowFixture(root, "r1", plan, "init");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("top-level run-state.json is NOT a query face (subflow-aware topology)", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    const runDir = join(root, "_tmp", "r1");
    // Hand-written top-level file carrying a COMPLETED subflowRuns entry for
    // the plan (append-on-completion shape) — the gate must IGNORE it and
    // deny, because the per-plan child-file face is the only query path.
    mkdirSync(runDir, { recursive: true });
    writeFileSync(join(runDir, "run-state.json"), JSON.stringify({
      runId: "r1", status: "completed",
      steps: [{ name: "EXEC_PLANS", type: "subflow", status: "completed",
        subflowRuns: [{ forEachIndex: 0, forEachItem: resolve(plan), file: "run-state-EXEC_PLANS-1-0.json", status: "completed" }] }],
    }), "utf8");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    // No child file exists → no evidence surface → D3 allow + note (top-level
    // evidence invisible by design). The hand-written top-level shape must
    // never flip this to deny NOR to an evidence-backed allow.
    assert.equal(d.kind, "allow");
    assert.match(d.note, /no run-state evidence surface/);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

/* ── 3. path domain + normalization ──────────────────────────────────────── */

test("path domain: default docs/plans and missions/*.json custom plansDir are gated", () => {
  const root = tmpProject();
  try {
    mkdirSync(join(root, "missions"), { recursive: true });
    writeFileSync(join(root, "missions", "demo.json"), JSON.stringify({
      name: "demo", roadmapPath: "docs/roadmap", plansDir: "docs/plans/custom", flowName: "x",
    }), "utf8");
    const custom = writePlan(root, "docs/plans/custom/c.md", "active");
    const std = writePlan(root, "docs/plans/d/d.md", "active");
    const outside = join(root, "docs", "notes", "n.md");
    mkdirSync(join(root, "docs", "notes"), { recursive: true });
    writeFileSync(outside, "> Status: completed\n", "utf8");
    for (const p of [custom, std]) {
      engineSubflowFixture(root, "r1", p, "failed");
      const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: p, content: "> Plan Status: completed\n" } }, fsGateIo);
      assert.equal(d.kind, "deny", `plans-root path must be gated: ${p}`);
    }
    // Non-plan .md with a completed status line: NOT under any known plans
    // root → passthrough even with a deny-shaped fixture present.
    const d2 = evaluatePlanStatusGate({ name: "write", arguments: { file_path: outside, content: "> Status: completed\nmore\n" } }, fsGateIo);
    assert.equal(d2.kind, "allow");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("path normalization: relative target path and .. segments still match forEachItem", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    const cwd = process.cwd();
    process.chdir(root);
    try {
      const rel = evaluatePlanStatusGate({ name: "write", arguments: { file_path: PLAN_REL, content: "> Plan Status: completed\n" } }, fsGateIo);
      assert.equal(rel.kind, "deny", "relative file_path must normalize onto the absolute forEachItem");
      const dotted = evaluatePlanStatusGate({
        name: "write",
        arguments: { file_path: join(root, "docs", "plans", "demo", "..", "demo", "x.md"), content: "> Plan Status: completed\n" },
      }, fsGateIo);
      assert.equal(dotted.kind, "deny", "`..` segments must resolve before comparison");
    } finally {
      process.chdir(cwd);
    }
  } finally { rmSync(root, { recursive: true, force: true }); }
});

/* ── 4. wiring shape (fake ctx capture) ──────────────────────────────────── */

test("registerPlanStatusGate: subscribes to tools/pre-execute, deny verbatim, allow delegates to next, returns disposer", async () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    engineSubflowFixture(root, "r1", plan, "failed");
    let captured = null;
    let disposed = false;
    const fakeCtx = {
      on(name, listener) { assert.equal(name, "tools/pre-execute"); captured = listener; return () => { disposed = true; }; },
    };
    const warns = [];
    const dispose = registerPlanStatusGate(fakeCtx, { warn: (m) => warns.push(m) });
    assert.equal(typeof dispose, "function");

    const denied = await captured({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, async () => ({ kind: "allow" }));
    assert.equal(denied.kind, "deny");
    assert.match(denied.reason, /plan-status gate/);
    assert.equal(warns.length, 1);

    const passed = await captured({ name: "write", arguments: { file_path: plan, content: "> Plan Status: draft\n" } }, async () => ({ kind: "allow" }));
    assert.deepEqual(passed, { kind: "allow" });

    const noted = [];
    const fakeCtx2 = {
      on(name, listener) { captured = listener; return () => {}; },
    };
    registerPlanStatusGate(fakeCtx2, { info: (m) => noted.push(m) });
    const allowed = await captured(
      { name: "write", arguments: { file_path: join(root, "docs", "plans", "demo", "fresh.md"), content: "> Plan Status: completed\n" } },
      async () => ({ kind: "allow" }),
    );
    assert.deepEqual(allowed, { kind: "allow" });
    assert.equal(noted.length, 1, "D3 observation note logged");

    dispose();
    assert.equal(disposed, true, "returned disposer unsubscribes");
  } finally { rmSync(root, { recursive: true, force: true }); }
});

/* ── 5. boundary sanity: _tmp scan only picks run-state-*.json children ──── */

test("run dir scan ignores draft jobs and non-state files", () => {
  const root = tmpProject();
  try {
    const plan = writePlan(root, PLAN_REL, "active");
    const runDir = join(root, "_tmp", "draft-1-mission-draft");
    mkdirSync(runDir, { recursive: true });
    writeFileSync(join(runDir, "draft-state.json"), JSON.stringify({ phase: "draft", status: "running" }), "utf8");
    writeFileSync(join(runDir, "notes.txt"), "junk", "utf8");
    const d = evaluatePlanStatusGate({ name: "write", arguments: { file_path: plan, content: "> Plan Status: completed\n" } }, fsGateIo);
    assert.equal(d.kind, "allow");
    assert.match(d.note, /no run-state evidence surface/);
    assert.equal(readdirSync(join(root, "_tmp")).length, 1);
  } finally { rmSync(root, { recursive: true, force: true }); }
});
